config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "lists#index"


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :lists, only: [:index, :show, :new, :create] do
      resources :bookmarks, only: [:new, :create, :destroy]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }, presence: true
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo

  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:destroy]
  before_action :set_list, only: [:new, :create, :destroy]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list), notice: 'Bookmark was successfully created.'
    else
      render 'lists/show'
    end
  end


  # def destroy
  #   list = @bookmark.list
  #   @bookmark.destroy
  #   redirect_to list_path(list)
  # end
  def destroy
    @bookmark.destroy
    redirect_to list_path(@list), notice: 'Bookmark was successfully deleted.'
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end

end

app/controllers/lists_controller.rb
# app/controllers/lists_controller.rb

class ListsController < ApplicationController
  before_action :set_list, only: [:show]

  def index
    @lists = List.all
  end

  def show
    @movies = @list.movies
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(params_list)
    if @list.save
      redirect_to root_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def params_list
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_form_modal.html.erb
<!-- app/views/bookmarks/_form_modal.html.erb -->

<div class="modal fade" id="addBookmarkModal" tabindex="-1" aria-labelledby="addBookmarkModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addBookmarkModalLabel">Add Movie</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@list, @bookmark], remote: true do |f| %>
          <%= f.association :movie %>
          <%= f.input :comment, label: "Comment" %>
          <%= f.button :submit, class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookmarks/new.html.erb
  <h2>Add movies</h2>

  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.association :movie %>
    <%= f.input :comment, label: "Comment" %>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
     <i class="fa-solid fa-film"></i>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
             <%= link_to "My lists", root_path, class: "navbar-brand" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Add a new list", new_list_path, class: "navbar-brand" %>
          </li>

        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>



    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<!-- app/views/lists/index.html.erb -->

<!-- Add the new banner with the provided image URL -->
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1513106580091-1d82408b8cd6?q=80&w=2976&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);">
  <div class="container">
    <h1><strong>My Lists!</strong></h1>
  </div>
</div>

<div class="container mt-5">
  <h1 class="mb-4">My Lists</h1>

  <div class="row">
    <% @lists.each do |list| %>
      <div class="col-md-4 mb-4">
        <div class="card">
          <% if list.photo.attached? %>
            <%= cl_image_tag(list.photo.key, class: "card-img-top", alt: list.name) %>
          <% elsif list.movies.present? %>
            <!-- Add the first image of the movie if the list has movies and the poster_url is present -->
            <%= image_tag(list.movies.first.poster_url, class: "card-img-top", alt: list.name) %>
          <% else %>
            <!-- Add a default image or message if the list has no movies or the poster_url is not present -->
            <%= image_tag("https://images.unsplash.com/photo-1699190375905-3cac33bbdbb1?q=80&w=3132&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", class: "card-img-top", alt: "Default Image") %>
          <% end %>

          <div class="card-body">
            <h5 class="card-title"><%= list.name %></h5>
            <a href="<%= list_path(list) %>" class="btn btn-primary">View List</a>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>



  <div class="mt-4">
    <%= link_to "Create a list", new_list_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/lists/new.html.erb
<!-- app/views/lists/new.html.erb -->

<h1>Add a list with a selection of movies using simple form</h1>

<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit %>
<% end %>

<%= link_to "Go back to homepage", root_path %>

app/views/lists/show.html.erb
<!-- app/views/lists/show.html.erb -->

<div class="container">
  <h1><%= @list.name %></h1>

  <h2>Movies in the list</h2>
  <div class="row">
    <% @list.bookmarks.each do |bookmark| %>
      <div class="col-md-4">
        <div class="card mb-4">
          <img src="<%= bookmark.movie.poster_url %>" class="card-img-top" alt="<%= bookmark.movie.title %>">
          <div class="card-body">
            <h5 class="card-title"><%= bookmark.movie.title %></h5>
            <p class="card-text"><%= bookmark.movie.overview %></p>
            <%= link_to "Delete", list_bookmark_path(@list, bookmark), method: :delete, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <!-- Button trigger modal -->
  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addBookmarkModal">
    Add a Bookmark
  </button>

  <!-- Include the modal -->
  <%= render 'bookmarks/form_modal' %>
</div>